server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: ${NOTIFICATION_DB_URL}
    username: ${NOTIFICATION_DB_USERNAME}
    password: ${NOTIFICATION_DB_PASSWORD}
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${SMTP_AUTH}
          starttls:
            enable: ${SMTP_STARTTLS_ENABLE}

banquito:
  internal:
    service-key: ${INTERNAL_SERVICE_KEY}
  security:
    jwt:
      issuer: ${JWT_ISSUER}
      secret: ${JWT_SECRET}
  grpc:
    server:
      port: ${NOTIFICATION_GRPC_PORT}
  notification:
    delivery:
      mode: ${NOTIFICATION_DELIVERY_MODE}
      provider: ${NOTIFICATION_PROVIDER}
      from: ${SMTP_FROM}
      reply-to: ${SMTP_REPLY_TO}
